### ISSUE TITLE
Fix Connectivity Strategies

### ISSUE THREAD

**Issue by lojedaa** [ISIS-3510-Mobiles/Kotlin#38]
Description:

The app currently experiences inconsistent behavior during network changes, such as switching between Wi-Fi and mobile data or operating offline. Users face issues like delayed reconnections, failed data syncing, and lack of clear feedback when connectivity is disrupted. This issue aims to address these challenges by refining the app's connectivity handling logic and enhancing its offline mode to ensure critical functionalities remain accessible.

Key tasks include optimizing reconnection strategies, implementing a robust offline mode with queuing for unsynced actions, and providing clearer user feedback during network disruptions. The goal is to ensure seamless transitions between network states, reduce user frustration, and improve the overall reliability of the app's connectivity features.

**Comment by Feru34** [comment]
Everything seems clear and well-structured! Your explanation highlights the current challenges with connectivity transitions and provides a focused approach to resolving them. The emphasis on refining reconnection strategies, enhancing offline functionality, and improving user feedback is spot on. Implementing these improvements will likely make the app's connectivity experience more seamless and user-friendly. The outlined goals and tasks align well with the objective of increasing reliability and reducing frustration. Great job!
